### ISSUE TITLE
Alias using SQL Builder

### ISSUE THREAD

**Issue by johnnestebann** [popphp/pop-db#2]
Hi! I'm having problems setting alias using sql builder.
When I do
`$sql = User::db()->createSql();`
`$sql = $sql->select([
    'user.id' => 'idUser'
])->from(User::table())`

I supposed it's SELECT user.id AS idUser FROM user

I get a:
<b>Warning</b>: SQLite3::prepare(): Unable to prepare statement: 1, near &quot;.&quot;: syntax error in
<b>/home/user/pop/vendor/popphp/pop-db/src/Adapter/Sqlite.php</b> on line <b>140</b><br /><b>Fatal error</b>: Uncaught TypeError: Argument 1 passed to Pop\Http\AbstractHttp::addHeaders() must be of the type array, null given

I'don't know how to resolve it! Thanks in advance!

**Comment by nicksagona** [comment]
So you need to flip the array key and value. Instead of: 
```php
$sql->select([ 'user.id' => 'idUser' ])->from(User::table());
```
it needs to be:
```php
$sql->select([ 'idUser' => 'user.id' ])->from(User::table());
```
The reason being that it uses the key to determine if there's an alias or not. If the key is numeric, it doesn't use an alias. If the key is a string (not numeric) it creates the alias. So for example, you can mix and match like this:

```php
$sql->select([
    'idUser' => 'user.id',
    'username',
    'email',
    'userPhone' => 'user.phone'
])->from(User::table());
```
and that will create:

```sql
SELECT "user"."id" AS "idUser", "username", "email", "user"."phone" AS "userPhone" FROM "user"
```

I know it might be a little confusing, but I'll be clearing it up in the updated/improved docs for v4.5

**Comment by johnnestebann** [comment]
Thanks!
